"""Add customer_id to sales

Revision ID: 3c622516dabe
Revises: d97f007a9faf
Create Date: 2026-05-08 23:26:21.513139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c622516dabe'
down_revision = 'd97f007a9faf'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.alter_column('cashier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=False)
        # Removed the incorrect items type change
        batch_op.create_foreign_key(
            'fk_sales_customer_id',
            'customers',
            ['customer_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('items',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('cashier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
