"""Add flagged column to Product

Revision ID: 59f78384930e
Revises: fb7e03bb202d
Create Date: 2026-05-20 23:36:26.331300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f78384930e'
down_revision = 'fb7e03bb202d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('items',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    # ### end Alembic commands ###
