"""Add discount column to Sale

Revision ID: 94535519ec2c
Revises: 59f78384930e
Create Date: 2026-05-20 23:47:55.660579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94535519ec2c'
down_revision = '59f78384930e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('voided', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('voided')
        batch_op.drop_column('discount')

    
    # ### end Alembic commands ###
