"""Add price column to SaleItem

Revision ID: cd202859c317
Revises: 36d1ee4f2aad
Create Date: 2026-05-02 15:19:40.205772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd202859c317'
down_revision = '36d1ee4f2aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
