"""Add discount column to SaleItem

Revision ID: fb7e03bb202d
Revises: 3c622516dabe
Create Date: 2026-05-18 21:40:46.378273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7e03bb202d'
down_revision = '3c622516dabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('items',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
